version: "3.7"

services:
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging: &logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: postgres:12

  ngrok:
    command: $NGROK_COMMAND
    depends_on:
      - astoria-server
    logging: *logging
    image: wernight/ngrok:latest

  astoria-server:
    build:
      context: ./server
      target: development
    command: mix phx.server
    depends_on:
      - astoria-analysis
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SQS_QUEUE_INPUT
      - AWS_SQS_QUEUE_OUTPUT
      - GITHUB_APP_ID
      - GITHUB_APP_PRIVATE_KEY=/usr/src/app/priv/keys/github_app_key_development.pem
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
    logging: *logging
    ports:
      - "4000:4000"
    user: "1000"
    volumes:
      - ./passwd:/etc/passwd
      - ./server:/usr/src/app
      - home:/home/server
      - opt:/opt

  astoria-analysis:
    build:
      context: ./analysis
    logging: *logging
    ports:
      - "8000:8000"
    user: "1000"
    volumes:
      - ./analysis:/usr/src/app

  pgadmin:
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
      - "5000:80"

  relay-compiler:
    build:
      context: ./server
      target: development
    command: ./node_modules/relay-compiler/bin/relay-compiler --src ./src --schema ./src/schema.json --watch
    logging: *logging
    user: "1000"
    working_dir: /usr/src/app/assets/
    volumes:
      - ./passwd:/etc/passwd
      - ./server:/usr/src/app
      - home:/home/server

volumes:
  home:
  opt:
