version: "3.7"

services:
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging: &logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: postgres:11

  astoria-server:
    depends_on:
      - postgres
    image: ${IMAGE_PATH_LATEST_SERVER}
    logging: *logging
