---
- name: Setup
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    deploy_image_file_local_analysis: '{{lookup("env","HOME")}}/analysis_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_file_local_server: '{{lookup("env","HOME")}}/server_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_name_analysis: 'astoria/astoria-analysis:{{lookup("env","SHA")}}'
    deploy_image_name_server: 'astoria/astoria-server:{{lookup("env","SHA")}}'
  tasks:
    - pip:
        name: docker

    - name: Build server deployment image
      docker_image:
        name: "{{deploy_image_name_server}}"
        build:
          cache_from: '{{lookup("env","IMAGE_PATH_LATEST_SERVER")}}'
          dockerfile: Dockerfile
          path: ../server
          target: deploy
          pull: no
        source: build

    - name: Build analysis deployment image
      docker_image:
        name: "{{deploy_image_name_analysis}}"
        build:
          cache_from: '{{lookup("env","IMAGE_PATH_LATEST_ANALYSIS")}}'
          dockerfile: Dockerfile
          path: ../analysis
          pull: no
        source: build

    - name: Save server locally before copy
      docker_image:
        name: "{{deploy_image_name_server}}"
        archive_path: "{{deploy_image_file_local_server}}"
        source: local

    - name: Save analysis locally before copy
      docker_image:
        name: "{{deploy_image_name_analysis}}"
        archive_path: "{{deploy_image_file_local_analysis}}"
        source: local

    - name: Export ssh key
      copy:
        src: id_ed25519_astoria.enc
        dest: '{{lookup("env","HOME")}}/id_ed25519_astoria'
        mode: 0600
        owner: "{{ ansible_user_id }}"

- name: Deploy
  hosts: app
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_private_key_file: '{{lookup("env","HOME")}}/id_ed25519_astoria'
    deploy_image_file_local_analysis: '{{lookup("env","HOME")}}/analysis_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_file_local_server: '{{lookup("env","HOME")}}/server_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_file_remote_analysis: '/tmp/analysis_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_file_remote_server: '/tmp/server_deploy_{{lookup("env","SHA")}}.tar'
    deploy_image_name_analysis: 'astoria/astoria-analysis:{{lookup("env","SHA")}}'
    deploy_image_name_server: 'astoria/astoria-server:{{lookup("env","SHA")}}'
  tasks:
    - pip:
        name: docker

    - name: Copy private key to remote
      copy:
        src: github_app_key.enc
        dest: "/root/github_app_key.pem"

    - name: Copy server image file to remote
      copy:
        src: "{{deploy_image_file_local_server}}"
        dest: "{{deploy_image_file_remote_server}}"

    - name: Copy analysis image file to remote
      copy:
        src: "{{deploy_image_file_local_analysis}}"
        dest: "{{deploy_image_file_remote_analysis}}"

    - name: Load server image
      docker_image:
        name: "{{deploy_image_name_server}}"
        load_path: "{{deploy_image_file_remote_server}}"
        source: load

    - name: Load analysis image
      docker_image:
        name: "{{deploy_image_name_analysis}}"
        load_path: "{{deploy_image_file_remote_analysis}}"
        source: load

    - name: Run migrations
      docker_container:
        name: astoria-migrations
        image: "{{deploy_image_name_server}}"
        restart_policy: no
        state: started
        command: bin/astoria eval "Astoria.Release.migrate"
        env: &env
          DATABASE_URL: "{{ database_url }}"
          GITHUB_APP_ID: "91034"
          GITHUB_APP_PRIVATE_KEY: /usr/src/app/priv/keys/github_app_key.pem
          GITHUB_CLIENT_ID: Iv1.72f681082d3f83aa
          GITHUB_CLIENT_SECRET: "{{ github_client_secret }}"
          SECRET_KEY_BASE: "{{ secret_key_base }}"
        volumes: &volumes
          - /root/github_app_key.pem:/usr/src/app/priv/keys/github_app_key.pem

    - name: Run seeds
      docker_container:
        name: astoria-seeds
        image: "{{deploy_image_name_server}}"
        restart_policy: no
        state: started
        command: bin/astoria eval "Astoria.Release.seed"
        env: *env
        volumes: *volumes

    - name: Create websites network
      docker_network:
        name: websites

    - name: Create astoria network
      docker_network:
        name: astoria

    - name: Ensure analysis running
      docker_container:
        name: astoria-analysis
        image: "{{deploy_image_name_analysis}}"
        log_driver: json-file
        restart_policy: unless-stopped
        log_options:
          "max-size": "5m"
          "max-file": "3"
        state: started
        networks:
          - name: websites
          - name: astoria
        env: *env
        volumes: *volumes

    - name: Ensure server running
      docker_container:
        name: astoria-server
        image: "{{deploy_image_name_server}}"
        log_driver: json-file
        restart_policy: unless-stopped
        log_options:
          "max-size": "5m"
          "max-file": "3"
        state: started
        networks:
          - name: websites
          - name: astoria
        env: *env
        volumes: *volumes

    - name: Remove uploaded server image
      file:
        path: "{{deploy_image_file_remote_server}}"
        state: absent

    - name: Remove uploaded analysis image
      file:
        path: "{{deploy_image_file_remote_analysis}}"
        state: absent
