name: CD

on:
  push:
    branches:
      - master

env:
  GPR_URL: "docker.pkg.github.com"
  GPR_USER: "rodeoclash"
  IMAGE_PATH_LATEST_SERVER: "docker.pkg.github.com/rodeoclash/astoria/astoria-server:latest"
  IMAGE_PATH_LATEST_ANALYSIS: "docker.pkg.github.com/rodeoclash/astoria/astoria-analysis:latest"
  SHA: ${{ github.SHA }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Log in to GPR
        run: docker login ${GPR_URL} -u ${GPR_USER} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the server image from GPR
        run: docker pull ${IMAGE_PATH_LATEST_SERVER}

      #- name: Pull the analysis image from GPR
      #  run: docker pull ${IMAGE_PATH_LATEST_ANALYSIS}

      - name: Run deploy playbook
        run: |
          make infra-deploy
